### ISSUE TITLE
Post-processing commands in tsconfig file not working

### ISSUE THREAD

**Issue by joswhite** [Phaiax/ArcticTypescript#50]
<p>Hi,</p>
<p>When I build the example Arctic Typescript project, "Common JS Module with Tests", the compiler fails to execute the post-processing commands given in the <code>tsconfig.json</code> file. I'm using Sublime Text Build 3083 on Windows 8 with Node 0.12.2.</p>
<p>Playing around with the issue I found out even the most simple post-processing command does not execute (i.e. <code>mkdir randomDirectory</code> or <code>echo hello</code>. After some investigation of the issue I found out that if I simply comment out line 60 of the file <code>lib/commands/Compiler.py</code>, which originally read <code>post_cmd = expand_variables(str(post_cmd), self.project, use_cache=True)</code>, the post processing commands work (see output from console below):</p>
<p><code>>>> ['node', 'C:\\Users\\JWhite\\AppData\\Roaming\\Sublime Text 3\\Packages\\ArcticTypescript\\bin\\node_modules\\typescript\\bin\\tsc', '--project', '.']</code></p>
<p><code>>> mocha -C -R spec built/test</code></p>
<p><code>  Array</code></p>
<p><code>    #indexOf()</code></p>
<p><code>      √ should return -1 when the value is not present</code></p>
<p><code>...</code></p>
<p>Can we get a fix for this? I apologize for not uncovering the true source of the bug; once I found out this worked I was content to stop there without trying to debug the offending <code>expand_variables</code> function. Thanks!</p>

**Comment by Phaiax** [comment]
fixed (release will follow in the next few hours)

**Comment by joswhite** [comment]
<p>Thanks for doing this commit. It still didn't fix the problem for me, so I investigated the issue further by debugging it and found out what my problem was. In <code>lib\system\Project.py</code> line 146 we call <code>startview.window().project_file_name()</code>, which is equivalent to <code>sublime.active_window().project_file_name()</code>. We store this value (the project file name) and then use it on line 482 of the file. The code on line 482 is called by the code that executes pre- and post-processing commands. To get it to return a valid path, one must have a <code>sublime-project</code> file for the project. So I added a <code>sublime-project</code> file to the project and had no more errors.</p>

<p>Hopefully anyone else who has this same problem is helped by my comment here. If you could mention on the home page that you must have a <code>sublime-project</code> file for the pre- and post-processing commands to work, that would be great! (It might also be nice to change the "Common JS Module with Tests" to have a project file so it works correctly as well.) That way others don't have to go through the same pain as me. :)</p>

<p>Please comment with any further ideas about this, or if I got any of this wrong. Thanks!</p>

**Comment by Phaiax** [comment]
no, i should fix that.
A few month ago, I have changed the project part, so that a project should never be neccessary. The problem is, that when I am doing testing, I always have the ArcticTypescript project loaded.
Thank you very much for pointing that out.

**Comment by joswhite** [comment]
Yes, if you could do that, then it would be even better! Thanks for your fast reply!
